# Generated by Django 5.1.2 on 2024-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='is_wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
