# Generated by Django 5.1.2 on 2024-11-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCart', '0002_wishlistitem_is_wishlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='is_wishlisted',
        ),
    ]
